---
title: "EvaluateBatch_original"
output: 
    html_document:
        toc: true
        toc_float: true
        toc_collapsed: true
        toc_depth: 3
        number_sections: true
        theme: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, message = FALSE, warning = FALSE
)
# sbatch -p epurdom --wrap="Rscript -e \"rmarkdown::render('EvaluateBatch_BSdist_Perez2022.Rmd')\""
library(dplyr)
library(ggplot2)
library(vegan)
safe_colorblind_palette <- c("#88CCEE", "#CC6677", "#DDCC77",
                             "#117733", "#332288", "#AA4499", 
                             "#44AA99", "#999933", "#882255",
                             "#661100", "#6699CC", "#888888")
colorBlindBlack8  <- c("#000000", "#E69F00", "#56B4E9", "#009E73", 
                       "#F0E442", "#0072B2", "#D55E00", "#CC79A7")  
```

```{r}

load("../../results/Perez2022/plot_df_batchupdate.Rda")
load("../../results/BatchStudy/dist_mat_Perez2022.Rda")
load("../../results/BatchStudy/dist_mat_Perez2022_scvi.Rda")
plot_df$batch_id <- paste0(plot_df$sample_uuid,"_", plot_df$Processing_Cohort)
meta <- unique(plot_df[, c("batch_id", "Processing_Cohort", "disease_state", "disease")])
rm(plot_df)



```





```{r}
O2 <- function(PERMANOVA){
  sumsq <- PERMANOVA$SumOfSqs
  n <- PERMANOVA$Df
  o2 <- (sumsq[1]-n[1]*(sumsq[2]/n[2]))/(sumsq[3] + sumsq[2]/n[2])
  return(o2)
}


```


```{r}
get_bootstrap_ids <- function(meta, batch, condition){
  bootstrap_sample_ids <- list()
  sample_ID <- 1:nrow(meta)

  for(i in unique(meta[,batch])){
    for(j in unique(meta[,condition])){
      # Generate bootstrap samples within the current class
      class_sample_ids <- sample_ID[meta[,batch] == i & meta[,condition] == j]

      bootstrap_sample_ids_cls <- sample(class_sample_ids, replace = TRUE)
    
      # Add the bootstrap sample IDs to the list
      bootstrap_sample_ids[[paste0(i,j)]] <- bootstrap_sample_ids_cls

    }
  }
  return(bootstrap_sample_ids)
}


get_stat <- function(distmat, meta, batch, condition){
  ANS_batch <- anosim(distmat, meta[,batch])
  ANS_condition <- anosim(distmat, meta[,condition])
  ANO_batch <- adonis2(distmat ~meta[,batch])
  ANO_condition <- adonis2(distmat ~meta[,condition])
  O2_batch = O2(ANO_batch)
  O2_condition = O2(ANO_condition)
  
  return(list(O2_batch, O2_condition, ANS_batch$statistic, ANS_condition$statistic))
}
```

# bootstrap

```{r}
stat_list = list()
for(i in 1:100){
    set.seed(i)
    boot_id <- unlist(get_bootstrap_ids(meta, "Processing_Cohort", "disease_state"))
    meta_boot <- meta[boot_id,]
    GMM_PCA <- get_stat(dist_mat_GMM_PCA[boot_id, boot_id], meta_boot, batch = "Processing_Cohort", condition= "disease_state")
    GMM_Har_sam <-  get_stat(dist_mat_GMM_har_sample[boot_id, boot_id], meta_boot, batch = "Processing_Cohort", condition= "disease_state")
    GMM_Har_batch <-  get_stat(dist_mat_GMM_har_batch[boot_id, boot_id], meta_boot, batch = "Processing_Cohort", condition= "disease_state")

    KNN_PCA <- get_stat(dist_mat_KNN_PCA[boot_id, boot_id], meta_boot, batch = "Processing_Cohort", condition= "disease_state")
    KNN_Har_sam <-  get_stat(dist_mat_KNN_har_sample[boot_id, boot_id], meta_boot, batch = "Processing_Cohort", condition= "disease_state")
    KNN_Har_batch <-  get_stat(dist_mat_KNN_har_batch[boot_id, boot_id], meta_boot, batch = "Processing_Cohort", condition= "disease_state")
    
    GMM_scvi <- get_stat(dist_mat_GMM_scvi[boot_id, boot_id], meta_boot, batch = "Processing_Cohort", condition= "disease_state")
    GMM_scvi_sam <-  get_stat(dist_mat_GMM_scvi_sample[boot_id, boot_id], meta_boot, batch = "Processing_Cohort", condition= "disease_state")
    GMM_scvi_batch <-  get_stat(dist_mat_GMM_scvi_batch[boot_id, boot_id], meta_boot, batch = "Processing_Cohort", condition= "disease_state")

    KNN_scvi <- get_stat(dist_mat_KNN_scvi[boot_id, boot_id], meta_boot, batch = "Processing_Cohort", condition= "disease_state")
    KNN_scvi_sam <-  get_stat(dist_mat_KNN_scvi_sample[boot_id, boot_id], meta_boot, batch = "Processing_Cohort", condition= "disease_state")
    KNN_scvi_batch <-  get_stat(dist_mat_KNN_scvi_batch[boot_id, boot_id], meta_boot, batch = "Processing_Cohort", condition= "disease_state")
    
    stat_list[[i]] = list(GMM_PCA, GMM_Har_sam, GMM_Har_batch,
                          KNN_PCA, KNN_Har_sam, KNN_Har_batch,
                          GMM_scvi, GMM_scvi_sam, GMM_scvi_batch,
                          KNN_scvi, KNN_scvi_sam, KNN_scvi_batch)
}

save(stat_list, file = "../../results/BatchStudy/Perez2022_BSdist.Rda")
```

```{r}
load("../../results/BatchStudy/Perez2022_BSdist.Rda")

```


```{r}
GMM_PCA_O2_batch <- unlist(lapply(stat_list, function(x) x[[1]][[1]]))
GMM_PCA_O2_condition <- unlist(lapply(stat_list, function(x) x[[1]][[2]]))
GMM_PCA_ANS_batch <- unlist(lapply(stat_list, function(x) x[[1]][[3]]))
GMM_PCA_ANS_condition <- unlist(lapply(stat_list, function(x) x[[1]][[4]]))

GMM_har_sam_O2_batch <- unlist(lapply(stat_list, function(x) x[[2]][[1]]))
GMM_har_sam_O2_condition <- unlist(lapply(stat_list, function(x) x[[2]][[2]]))
GMM_har_sam_ANS_batch <- unlist(lapply(stat_list, function(x) x[[2]][[3]]))
GMM_har_sam_ANS_condition <- unlist(lapply(stat_list, function(x) x[[2]][[4]]))

GMM_har_batch_O2_batch <- unlist(lapply(stat_list, function(x) x[[3]][[1]]))
GMM_har_batch_O2_condition <- unlist(lapply(stat_list, function(x) x[[3]][[2]]))
GMM_har_batch_ANS_batch <- unlist(lapply(stat_list, function(x) x[[3]][[3]]))
GMM_har_batch_ANS_condition <- unlist(lapply(stat_list, function(x) x[[3]][[4]]))

```

```{r}
KNN_PCA_O2_batch <- unlist(lapply(stat_list, function(x) x[[4]][[1]]))
KNN_PCA_O2_condition <- unlist(lapply(stat_list, function(x) x[[4]][[2]]))
KNN_PCA_ANS_batch <- unlist(lapply(stat_list, function(x) x[[4]][[3]]))
KNN_PCA_ANS_condition <- unlist(lapply(stat_list, function(x) x[[4]][[4]]))

KNN_har_sam_O2_batch <- unlist(lapply(stat_list, function(x) x[[5]][[1]]))
KNN_har_sam_O2_condition <- unlist(lapply(stat_list, function(x) x[[5]][[2]]))
KNN_har_sam_ANS_batch <- unlist(lapply(stat_list, function(x) x[[5]][[3]]))
KNN_har_sam_ANS_condition <- unlist(lapply(stat_list, function(x) x[[5]][[4]]))

KNN_har_batch_O2_batch <- unlist(lapply(stat_list, function(x) x[[6]][[1]]))
KNN_har_batch_O2_condition <- unlist(lapply(stat_list, function(x) x[[6]][[2]]))
KNN_har_batch_ANS_batch <- unlist(lapply(stat_list, function(x) x[[6]][[3]]))
KNN_har_batch_ANS_condition <- unlist(lapply(stat_list, function(x) x[[6]][[4]]))

```


```{r}
GMM_scvi_O2_batch <- unlist(lapply(stat_list, function(x) x[[7]][[1]]))
GMM_scvi_O2_condition <- unlist(lapply(stat_list, function(x) x[[7]][[2]]))
GMM_scvi_ANS_batch <- unlist(lapply(stat_list, function(x) x[[7]][[3]]))
GMM_scvi_ANS_condition <- unlist(lapply(stat_list, function(x) x[[7]][[4]]))

GMM_scvi_sam_O2_batch <- unlist(lapply(stat_list, function(x) x[[8]][[1]]))
GMM_scvi_sam_O2_condition <- unlist(lapply(stat_list, function(x) x[[8]][[2]]))
GMM_scvi_sam_ANS_batch <- unlist(lapply(stat_list, function(x) x[[8]][[3]]))
GMM_scvi_sam_ANS_condition <- unlist(lapply(stat_list, function(x) x[[8]][[4]]))

GMM_scvi_batch_O2_batch <- unlist(lapply(stat_list, function(x) x[[9]][[1]]))
GMM_scvi_batch_O2_condition <- unlist(lapply(stat_list, function(x) x[[9]][[2]]))
GMM_scvi_batch_ANS_batch <- unlist(lapply(stat_list, function(x) x[[9]][[3]]))
GMM_scvi_batch_ANS_condition <- unlist(lapply(stat_list, function(x) x[[9]][[4]]))

```

```{r}
KNN_scvi_O2_batch <- unlist(lapply(stat_list, function(x) x[[10]][[1]]))
KNN_scvi_O2_condition <- unlist(lapply(stat_list, function(x) x[[10]][[2]]))
KNN_scvi_ANS_batch <- unlist(lapply(stat_list, function(x) x[[10]][[3]]))
KNN_scvi_ANS_condition <- unlist(lapply(stat_list, function(x) x[[10]][[4]]))

KNN_scvi_sam_O2_batch <- unlist(lapply(stat_list, function(x) x[[11]][[1]]))
KNN_scvi_sam_O2_condition <- unlist(lapply(stat_list, function(x) x[[11]][[2]]))
KNN_scvi_sam_ANS_batch <- unlist(lapply(stat_list, function(x) x[[11]][[3]]))
KNN_scvi_sam_ANS_condition <- unlist(lapply(stat_list, function(x) x[[11]][[4]]))

KNN_scvi_batch_O2_batch <- unlist(lapply(stat_list, function(x) x[[12]][[1]]))
KNN_scvi_batch_O2_condition <- unlist(lapply(stat_list, function(x) x[[12]][[2]]))
KNN_scvi_batch_ANS_batch <- unlist(lapply(stat_list, function(x) x[[12]][[3]]))
KNN_scvi_batch_ANS_condition <- unlist(lapply(stat_list, function(x) x[[12]][[4]]))

```

```{r}
GMM_PCA_O2_batch_sd <- sd(GMM_PCA_O2_batch)
GMM_PCA_O2_condition_sd <- sd(GMM_PCA_O2_condition)
GMM_PCA_ANS_batch_sd <- sd(GMM_PCA_ANS_batch)
GMM_PCA_ANS_condition_sd <- sd(GMM_PCA_ANS_condition)
GMM_har_sam_O2_batch_sd <- sd(GMM_har_sam_O2_batch)
GMM_har_sam_O2_condition_sd <- sd(GMM_har_sam_O2_condition)
GMM_har_sam_ANS_batch_sd <- sd(GMM_har_sam_ANS_batch)
GMM_har_sam_ANS_condition_sd <- sd(GMM_har_sam_ANS_condition)
GMM_har_batch_O2_batch_sd <- sd(GMM_har_batch_O2_batch)
GMM_har_batch_O2_condition_sd <- sd(GMM_har_batch_O2_condition)
GMM_har_batch_ANS_batch_sd <- sd(GMM_har_batch_ANS_batch)
GMM_har_batch_ANS_condition_sd <- sd(GMM_har_batch_ANS_condition)

KNN_PCA_O2_batch_sd <- sd(KNN_PCA_O2_batch)
KNN_PCA_O2_condition_sd <- sd(KNN_PCA_O2_condition)
KNN_PCA_ANS_batch_sd <- sd(KNN_PCA_ANS_batch)
KNN_PCA_ANS_condition_sd <- sd(KNN_PCA_ANS_condition)
KNN_har_sam_O2_batch_sd <- sd(KNN_har_sam_O2_batch)
KNN_har_sam_O2_condition_sd <- sd(KNN_har_sam_O2_condition)
KNN_har_sam_ANS_batch_sd <- sd(KNN_har_sam_ANS_batch)
KNN_har_sam_ANS_condition_sd <- sd(KNN_har_sam_ANS_condition)
KNN_har_batch_O2_batch_sd <- sd(KNN_har_batch_O2_batch)
KNN_har_batch_O2_condition_sd <- sd(KNN_har_batch_O2_condition)
KNN_har_batch_ANS_batch_sd <- sd(KNN_har_batch_ANS_batch)
KNN_har_batch_ANS_condition_sd <- sd(KNN_har_batch_ANS_condition)


GMM_scvi_O2_batch_sd <- sd(GMM_scvi_O2_batch)
GMM_scvi_O2_condition_sd <- sd(GMM_scvi_O2_condition)
GMM_scvi_ANS_batch_sd <- sd(GMM_scvi_ANS_batch)
GMM_scvi_ANS_condition_sd <- sd(GMM_scvi_ANS_condition)
GMM_scvi_sam_O2_batch_sd <- sd(GMM_scvi_sam_O2_batch)
GMM_scvi_sam_O2_condition_sd <- sd(GMM_scvi_sam_O2_condition)
GMM_scvi_sam_ANS_batch_sd <- sd(GMM_scvi_sam_ANS_batch)
GMM_scvi_sam_ANS_condition_sd <- sd(GMM_scvi_sam_ANS_condition)
GMM_scvi_batch_O2_batch_sd <- sd(GMM_scvi_batch_O2_batch)
GMM_scvi_batch_O2_condition_sd <- sd(GMM_scvi_batch_O2_condition)
GMM_scvi_batch_ANS_batch_sd <- sd(GMM_scvi_batch_ANS_batch)
GMM_scvi_batch_ANS_condition_sd <- sd(GMM_scvi_batch_ANS_condition)

KNN_scvi_O2_batch_sd <- sd(KNN_scvi_O2_batch)
KNN_scvi_O2_condition_sd <- sd(KNN_scvi_O2_condition)
KNN_scvi_ANS_batch_sd <- sd(KNN_scvi_ANS_batch)
KNN_scvi_ANS_condition_sd <- sd(KNN_scvi_ANS_condition)
KNN_scvi_sam_O2_batch_sd <- sd(KNN_scvi_sam_O2_batch)
KNN_scvi_sam_O2_condition_sd <- sd(KNN_scvi_sam_O2_condition)
KNN_scvi_sam_ANS_batch_sd <- sd(KNN_scvi_sam_ANS_batch)
KNN_scvi_sam_ANS_condition_sd <- sd(KNN_scvi_sam_ANS_condition)
KNN_scvi_batch_O2_batch_sd <- sd(KNN_scvi_batch_O2_batch)
KNN_scvi_batch_O2_condition_sd <- sd(KNN_scvi_batch_O2_condition)
KNN_scvi_batch_ANS_batch_sd <- sd(KNN_scvi_batch_ANS_batch)
KNN_scvi_batch_ANS_condition_sd <- sd(KNN_scvi_batch_ANS_condition)
```



## visualization

```{r}
load("../../results/BatchStudy/Perez2022_statRda")
```


```{r}
Ori_R_boot <- data.frame(values = c(GMM_PCA_ANS_batch, GMM_PCA_ANS_condition,
                        KNN_PCA_ANS_batch, KNN_PCA_ANS_condition,
                        GMM_scvi_ANS_batch, GMM_scvi_ANS_condition,
                        KNN_scvi_ANS_batch, KNN_scvi_ANS_condition),
                      Dens = rep(rep(c("GMM","KNN"),each = 200),2),
                      Reduction = c(rep("PCA",400), rep("ScVI",400)),
                      Compare = rep(rep(c("Batch","Condition"),each = 100),4))

Ori_O2_boot <- data.frame(values = c(GMM_PCA_O2_batch, GMM_PCA_O2_condition,
                        KNN_PCA_O2_batch, KNN_PCA_O2_condition,
                        GMM_scvi_O2_batch, GMM_scvi_O2_condition,
                        KNN_scvi_O2_batch, KNN_scvi_O2_condition),
                      Dens = rep(rep(c("GMM","KNN"),each = 200),2),
                      Reduction = c(rep("PCA",400), rep("ScVI",400)),
                      Compare = rep(rep(c("Batch","Condition"),each = 100),4))

Ori_R <- R_data[R_data$DimReduc == "Original",]
Ori_R$comb <- paste0(Ori_R$Dens, ",", Ori_R$Correction)
Ori_R$Compare = Ori_R$Group
ggplot(Ori_R_boot, aes(x = paste0(Dens, ",", Reduction), y = values)) +
  geom_boxplot() +
  geom_point(data = Ori_R, aes(x = comb, y = Value), col = "red", size = 2)+
    geom_jitter(color="black", size=0.4, alpha=0.9) +
  facet_wrap(~Compare) +
  xlab("Combination") +
  ggtitle("ANOSIM R Value, No Batch Correction") +
  theme_bw()+
    ylim(c(min(c(Ori_O2_boot$values, Ori_R_boot$values)), max(c(Ori_O2_boot$values, Ori_R_boot$values))))
```

```{r}


Ori_O2 <- O2_data[O2_data$DimReduc == "Original",]
Ori_O2$comb <- paste0(Ori_O2$Dens, ",", Ori_O2$Correction)
Ori_O2$Compare = Ori_R$Group
ggplot(Ori_O2_boot, aes(x = paste0(Dens, ",", Reduction), y = values)) +
  geom_boxplot() +
  geom_point(data = Ori_O2, aes(x = comb, y = Value), col = "red", size = 2)+
    geom_jitter(color="black", size=0.4, alpha=0.9) +
  facet_wrap(~Compare) +
  xlab("Combination") +
  ggtitle("Oemga^2 Value, No Batch Correction") +
  theme_bw()+
    ylim(c(min(c(Ori_O2_boot$values, Ori_R_boot$values)), max(c(Ori_O2_boot$values, Ori_R_boot$values))))
```

```{r}
Sam_R_boot <- data.frame(values = c(GMM_har_sam_ANS_batch, GMM_har_sam_ANS_condition,
                        KNN_har_sam_ANS_batch, KNN_har_sam_ANS_condition,
                        GMM_scvi_sam_ANS_batch, GMM_scvi_sam_ANS_condition,
                        KNN_scvi_sam_ANS_batch, KNN_scvi_sam_ANS_condition),
                      Dens = rep(rep(c("GMM","KNN"),each = 200),2),
                      Reduction = c(rep("PCA",400), rep("ScVI",400)),
                      Compare = rep(rep(c("Batch","Condition"),each = 100),4))

Sam_O2_boot <- data.frame(values = c(GMM_har_sam_O2_batch, GMM_har_sam_O2_condition,
                        KNN_har_sam_O2_batch, KNN_har_sam_O2_condition,
                        GMM_scvi_sam_O2_batch, GMM_scvi_sam_O2_condition,
                        KNN_scvi_sam_O2_batch, KNN_scvi_sam_O2_condition),
                      Dens = rep(rep(c("GMM","KNN"),each = 200),2),
                      Reduction = c(rep("PCA",400), rep("ScVI",400)),
                      Compare = rep(rep(c("Batch","Condition"),each = 100),4))

Sam_R <- R_data[R_data$DimReduc == "Correct, Sample",]
Sam_R$comb <- paste0(Sam_R$Dens, ",", Sam_R$Correction)
Sam_R$Compare = Sam_R$Group
ggplot(Sam_R_boot, aes(x = paste0(Dens, ",", Reduction), y = values)) +
  geom_boxplot() +
  geom_point(data = Sam_R, aes(x = comb, y = Value), col = "red", size = 2)+
    geom_jitter(color="black", size=0.4, alpha=0.9) +
  facet_wrap(~Compare,scales = "free_y") +
  xlab("Combination") +
  ggtitle("ANOSIM R Value, Batch Correction on Sample") +
  theme_bw()+
    ylim(c(min(c(Sam_O2_boot$values, Sam_R_boot$values)), max(c(Sam_O2_boot$values, Sam_R_boot$values))))
```

```{r}
Sam_O2_boot <- data.frame(values = c(GMM_har_sam_O2_batch, GMM_har_sam_O2_condition,
                        KNN_har_sam_O2_batch, KNN_har_sam_O2_condition,
                        GMM_scvi_sam_O2_batch, GMM_scvi_sam_O2_condition,
                        KNN_scvi_sam_O2_batch, KNN_scvi_sam_O2_condition),
                      Dens = rep(rep(c("GMM","KNN"),each = 200),2),
                      Reduction = c(rep("PCA",400), rep("ScVI",400)),
                      Compare = rep(rep(c("Batch","Condition"),each = 100),4))

Sam_O2 <- O2_data[O2_data$DimReduc == "Correct, Sample",]
Sam_O2$comb <- paste0(Sam_O2$Dens, ",", Sam_O2$Correction)
Sam_O2$Compare = Sam_O2$Group
ggplot(Sam_O2_boot, aes(x = paste0(Dens, ",", Reduction), y = values)) +
  geom_boxplot() +
  geom_point(data = Sam_O2, aes(x = comb, y = Value), col = "red", size = 2)+
    geom_jitter(color="black", size=0.4, alpha=0.9) +
  facet_wrap(~Compare,scales = "free_y") +
  xlab("Combination") +
  ggtitle("Oemga^2 Value, Batch Correction on Sample") +
  theme_bw()
```


```{r}
batch_R_boot <- data.frame(values = c(GMM_har_batch_ANS_batch, GMM_har_batch_ANS_condition,
                        KNN_har_batch_ANS_batch, KNN_har_batch_ANS_condition,
                        GMM_scvi_batch_ANS_batch, GMM_scvi_batch_ANS_condition,
                        KNN_scvi_batch_ANS_batch, KNN_scvi_batch_ANS_condition),
                      Dens = rep(rep(c("GMM","KNN"),each = 200),2),
                      Reduction = c(rep("PCA",400), rep("ScVI",400)),
                      Compare = rep(rep(c("Batch","Condition"),each = 100),4))

batch_R <- R_data[R_data$DimReduc == "Correct, Batch",]
batch_R$comb <- paste0(batch_R$Dens, ",", batch_R$Correction)
batch_R$Compare = batch_R$Group
ggplot(batch_R_boot, aes(x = paste0(Dens, ",", Reduction), y = values)) +
  geom_boxplot() +
  geom_point(data = batch_R, aes(x = comb, y = Value), col = "red", size = 2)+
    geom_jitter(color="black", size=0.4, alpha=0.9) +
  facet_wrap(~Compare,scales = "free_y") +
  xlab("Combination") +
  ggtitle("ANOSIM R Value, Batch Correction on Batch") +
  theme_bw()
```

```{r}
batch_O2_boot <- data.frame(values = c(GMM_har_batch_O2_batch, GMM_har_batch_O2_condition,
                        KNN_har_batch_O2_batch, KNN_har_batch_O2_condition,
                        GMM_scvi_batch_O2_batch, GMM_scvi_batch_O2_condition,
                        KNN_scvi_batch_O2_batch, KNN_scvi_batch_O2_condition),
                      Dens = rep(rep(c("GMM","KNN"),each = 200),2),
                      Reduction = c(rep("PCA",400), rep("ScVI",400)),
                      Compare = rep(rep(c("Batch","Condition"),each = 100),4))

batch_O2 <- O2_data[O2_data$DimReduc == "Correct, Batch",]
batch_O2$comb <- paste0(batch_O2$Dens, ",", batch_O2$Correction)
batch_O2$Compare = batch_O2$Group
ggplot(batch_O2_boot, aes(x = paste0(Dens, ",", Reduction), y = values)) +
  geom_boxplot() +
  geom_point(data = batch_O2, aes(x = comb, y = Value), col = "red", size = 2)+
    geom_jitter(color="black", size=0.4, alpha=0.9) +
  facet_wrap(~Compare,scales = "free_y") +
  xlab("Combination") +
  ggtitle("Oemga^2 Value, Batch Correction on Batch") +
  theme_bw()
```



# jackknife

```{r}
jackknife = function(distmat, meta, batch, condition){
  stat_list = ls()
  for(i in 1:nrow(distmat)){
    jk_dist <- distmat[-i,-i]
    jk_meta <- meta[-i,]
    stat_list[[i]] <- get_stat(distmat = jk_dist, meta = jk_meta, batch = batch, condition= condition)
  }
  return(stat_list)
}
```

```{r}
GMM_PCA <- jackknife(distmat = dist_mat_GMM_PCA, meta, "Processing_Cohort", "disease_state")
KNN_PCA <- jackknife(distmat = dist_mat_KNN_PCA, meta, "Processing_Cohort", "disease_state")
GMM_har_sam <- jackknife(distmat = dist_mat_GMM_har_sample, meta, "Processing_Cohort", "disease_state")
KNN_har_sam <- jackknife(distmat = dist_mat_KNN_har_sample, meta, "Processing_Cohort", "disease_state")
GMM_har_batch <- jackknife(distmat = dist_mat_GMM_har_batch, meta, "Processing_Cohort", "disease_state")
KNN_har_batch <- jackknife(distmat = dist_mat_KNN_har_batch, meta, "Processing_Cohort", "disease_state")


GMM_scvi <- jackknife(distmat = dist_mat_GMM_scvi, meta, "Processing_Cohort", "disease_state")
KNN_scvi <- jackknife(distmat = dist_mat_KNN_scvi, meta, "Processing_Cohort", "disease_state")
GMM_scvi_sam <- jackknife(distmat = dist_mat_GMM_scvi_sample, meta, "Processing_Cohort", "disease_state")
KNN_scvi_sam <- jackknife(distmat = dist_mat_KNN_scvi_sample, meta, "Processing_Cohort", "disease_state")
GMM_scvi_batch <- jackknife(distmat = dist_mat_GMM_scvi_batch, meta, "Processing_Cohort", "disease_state")
KNN_scvi_batch <- jackknife(distmat = dist_mat_KNN_scvi_batch, meta, "Processing_Cohort", "disease_state")

```



# Cell level bootstrap

```{r}
get_stat <- function(distmat, meta, batch, condition){
  ANS_batch <- anosim(distmat, meta[,batch])
  ANS_condition <- anosim(distmat, meta[,condition])
  ANO_batch <- adonis2(distmat ~meta[,batch])
  ANO_condition <- adonis2(distmat ~meta[,condition])
  O2_batch = O2(ANO_batch)
  O2_condition = O2(ANO_condition)
  
  return(c(O2_batch, O2_condition, ANS_batch$statistic, ANS_condition$statistic))
}
```


```{r}
stat_list = list()
for(i in 1:100){
  load(paste0("../../results/BatchStudy/BootStrap/Perez2022/Dim_EV/",i,".Rda"))
  dist_mat_GMM_PCA_sub <- dist_mat_GMM_PCA[sub_id, sub_id]
dist_mat_GMM_har_sample_sub <- dist_mat_GMM_har_sample[sub_id, sub_id]
dist_mat_GMM_har_site_sub <- dist_mat_GMM_har_site[sub_id, sub_id]
dist_mat_GMM_scvi_sub <- dist_mat_GMM_scvi[sub_id, sub_id]
dist_mat_GMM_scvi_sample_sub <- dist_mat_GMM_scvi_samp[sub_id, sub_id]
dist_mat_GMM_scvi_site_sub <- dist_mat_GMM_scvi_site[sub_id, sub_id]
dist_mat_KNN_PCA_sub <- dist_mat_KNN_PCA[sub_id, sub_id]
dist_mat_KNN_har_sample_sub <- dist_mat_KNN_har_sample[sub_id, sub_id]
dist_mat_KNN_har_sample_sub[which(dist_mat_KNN_har_sample_sub<0)] = 0
dist_mat_KNN_har_site_sub <- dist_mat_KNN_har_site[sub_id, sub_id]
dist_mat_KNN_scvi_sub <- dist_mat_KNN_scvi[sub_id, sub_id]
dist_mat_KNN_scvi_sample_sub <- dist_mat_KNN_scvi_samp[sub_id, sub_id]
dist_mat_KNN_scvi_site_sub <- dist_mat_KNN_scvi_site[sub_id, sub_id]

      GMM_PCA <- get_stat(dist_mat_GMM_PCA_sub, meta_sub, batch = "Site", condition= "Status")
    GMM_Har_sam <-  get_stat(dist_mat_GMM_har_sample_sub, meta_sub, batch = "Site", condition= "Status")
    GMM_Har_batch <-  get_stat(dist_mat_GMM_har_site_sub, meta_sub, batch = "Site", condition= "Status")

    KNN_PCA <- get_stat(dist_mat_KNN_PCA_sub, meta_sub, batch = "Site", condition= "Status")
    KNN_Har_sam <-  get_stat(dist_mat_KNN_har_sample_sub, meta_sub, batch = "Site", condition= "Status")
    KNN_Har_batch <-  get_stat(dist_mat_KNN_har_site_sub, meta_sub, batch = "Site", condition= "Status")
    
    GMM_scvi <- get_stat(dist_mat_GMM_scvi_sub, meta_sub, batch = "Site", condition= "Status")
    GMM_scvi_sam <-  get_stat(dist_mat_GMM_scvi_sample_sub, meta_sub, batch = "Site", condition= "Status")
    GMM_scvi_batch <-  get_stat(dist_mat_GMM_scvi_site_sub, meta_sub, batch = "Site", condition= "Status")

    KNN_scvi <- get_stat(dist_mat_KNN_scvi_sub, meta_sub, batch = "Site", condition= "Status")
    KNN_scvi_sam <-  get_stat(dist_mat_KNN_scvi_sample_sub, meta_sub, batch = "Site", condition= "Status")
    KNN_scvi_batch <-  get_stat(dist_mat_KNN_scvi_site_sub, meta_sub, batch = "Site", condition= "Status")
    
    stat_list[[i]] = list(GMM_PCA, GMM_Har_sam, GMM_Har_batch,
                          KNN_PCA, KNN_Har_sam, KNN_Har_batch,
                          GMM_scvi, GMM_scvi_sam, GMM_scvi_batch,
                          KNN_scvi, KNN_scvi_sam, KNN_scvi_batch)
}
```

```{r}
load("../../results/BatchStudy/Perez2022_BSdim_stat.Rda")
```


```{r}
GMM_PCA_O2_batch <- unlist(lapply(stat_list, function(x) x[[1]][[1]]))
GMM_PCA_O2_condition <- unlist(lapply(stat_list, function(x) x[[1]][[2]]))
GMM_PCA_ANS_batch <- unlist(lapply(stat_list, function(x) x[[1]][[3]]))
GMM_PCA_ANS_condition <- unlist(lapply(stat_list, function(x) x[[1]][[4]]))


GMM_har_sam_O2_batch <- unlist(lapply(stat_list, function(x) x[[2]][[1]]))
GMM_har_sam_O2_condition <- unlist(lapply(stat_list, function(x) x[[2]][[2]]))
GMM_har_sam_ANS_batch <- unlist(lapply(stat_list, function(x) x[[2]][[3]]))
GMM_har_sam_ANS_condition <- unlist(lapply(stat_list, function(x) x[[2]][[4]]))



GMM_har_batch_O2_batch <- unlist(lapply(stat_list, function(x) x[[3]][[1]]))
GMM_har_batch_O2_condition <- unlist(lapply(stat_list, function(x) x[[3]][[2]]))
GMM_har_batch_ANS_batch <- unlist(lapply(stat_list, function(x) x[[3]][[3]]))
GMM_har_batch_ANS_condition <- unlist(lapply(stat_list, function(x) x[[3]][[4]]))


```

```{r}
KNN_PCA_O2_batch <- unlist(lapply(stat_list, function(x) x[[4]][[1]]))
KNN_PCA_O2_condition <- unlist(lapply(stat_list, function(x) x[[4]][[2]]))
KNN_PCA_ANS_batch <- unlist(lapply(stat_list, function(x) x[[4]][[3]]))
KNN_PCA_ANS_condition <- unlist(lapply(stat_list, function(x) x[[4]][[4]]))

KNN_har_sam_O2_batch <- unlist(lapply(stat_list, function(x) x[[5]][[1]]))
KNN_har_sam_O2_condition <- unlist(lapply(stat_list, function(x) x[[5]][[2]]))
KNN_har_sam_ANS_batch <- unlist(lapply(stat_list, function(x) x[[5]][[3]]))
KNN_har_sam_ANS_condition <- unlist(lapply(stat_list, function(x) x[[5]][[4]]))

KNN_har_batch_O2_batch <- unlist(lapply(stat_list, function(x) x[[6]][[1]]))
KNN_har_batch_O2_condition <- unlist(lapply(stat_list, function(x) x[[6]][[2]]))
KNN_har_batch_ANS_batch <- unlist(lapply(stat_list, function(x) x[[6]][[3]]))
KNN_har_batch_ANS_condition <- unlist(lapply(stat_list, function(x) x[[6]][[4]]))


```


```{r}
GMM_scvi_O2_batch <- unlist(lapply(stat_list, function(x) x[[7]][[1]]))
GMM_scvi_O2_condition <- unlist(lapply(stat_list, function(x) x[[7]][[2]]))
GMM_scvi_ANS_batch <- unlist(lapply(stat_list, function(x) x[[7]][[3]]))
GMM_scvi_ANS_condition <- unlist(lapply(stat_list, function(x) x[[7]][[4]]))

GMM_scvi_sam_O2_batch <- unlist(lapply(stat_list, function(x) x[[8]][[1]]))
GMM_scvi_sam_O2_condition <- unlist(lapply(stat_list, function(x) x[[8]][[2]]))
GMM_scvi_sam_ANS_batch <- unlist(lapply(stat_list, function(x) x[[8]][[3]]))
GMM_scvi_sam_ANS_condition <- unlist(lapply(stat_list, function(x) x[[8]][[4]]))

GMM_scvi_batch_O2_batch <- unlist(lapply(stat_list, function(x) x[[9]][[1]]))
GMM_scvi_batch_O2_condition <- unlist(lapply(stat_list, function(x) x[[9]][[2]]))
GMM_scvi_batch_ANS_batch <- unlist(lapply(stat_list, function(x) x[[9]][[3]]))
GMM_scvi_batch_ANS_condition <- unlist(lapply(stat_list, function(x) x[[9]][[4]]))



```

```{r}
KNN_scvi_O2_batch <- unlist(lapply(stat_list, function(x) x[[10]][[1]]))
KNN_scvi_O2_condition <- unlist(lapply(stat_list, function(x) x[[10]][[2]]))
KNN_scvi_ANS_batch <- unlist(lapply(stat_list, function(x) x[[10]][[3]]))
KNN_scvi_ANS_condition <- unlist(lapply(stat_list, function(x) x[[10]][[4]]))

KNN_scvi_sam_O2_batch <- unlist(lapply(stat_list, function(x) x[[11]][[1]]))
KNN_scvi_sam_O2_condition <- unlist(lapply(stat_list, function(x) x[[11]][[2]]))
KNN_scvi_sam_ANS_batch <- unlist(lapply(stat_list, function(x) x[[11]][[3]]))
KNN_scvi_sam_ANS_condition <- unlist(lapply(stat_list, function(x) x[[11]][[4]]))

KNN_scvi_batch_O2_batch <- unlist(lapply(stat_list, function(x) x[[12]][[1]]))
KNN_scvi_batch_O2_condition <- unlist(lapply(stat_list, function(x) x[[12]][[2]]))
KNN_scvi_batch_ANS_batch <- unlist(lapply(stat_list, function(x) x[[12]][[3]]))
KNN_scvi_batch_ANS_condition <- unlist(lapply(stat_list, function(x) x[[12]][[4]]))




```

## sd comparison

```{r}
load("../../results/BatchStudy/Perez2022_stat.Rda")

```


```{r}
GMM_PCA_O2_batch_sd <- sd(GMM_PCA_O2_batch)
GMM_PCA_O2_condition_sd <- sd(GMM_PCA_O2_condition)
GMM_PCA_ANS_batch_sd <- sd(GMM_PCA_ANS_batch)
GMM_PCA_ANS_condition_sd <- sd(GMM_PCA_ANS_condition)
GMM_har_sam_O2_batch_sd <- sd(GMM_har_sam_O2_batch)
GMM_har_sam_O2_condition_sd <- sd(GMM_har_sam_O2_condition)
GMM_har_sam_ANS_batch_sd <- sd(GMM_har_sam_ANS_batch)
GMM_har_sam_ANS_condition_sd <- sd(GMM_har_sam_ANS_condition)
GMM_har_batch_O2_batch_sd <- sd(GMM_har_batch_O2_batch)
GMM_har_batch_O2_condition_sd <- sd(GMM_har_batch_O2_condition)
GMM_har_batch_ANS_batch_sd <- sd(GMM_har_batch_ANS_batch)
GMM_har_batch_ANS_condition_sd <- sd(GMM_har_batch_ANS_condition)

KNN_PCA_O2_batch_sd <- sd(KNN_PCA_O2_batch)
KNN_PCA_O2_condition_sd <- sd(KNN_PCA_O2_condition)
KNN_PCA_ANS_batch_sd <- sd(KNN_PCA_ANS_batch)
KNN_PCA_ANS_condition_sd <- sd(KNN_PCA_ANS_condition)
KNN_har_sam_O2_batch_sd <- sd(KNN_har_sam_O2_batch)
KNN_har_sam_O2_condition_sd <- sd(KNN_har_sam_O2_condition)
KNN_har_sam_ANS_batch_sd <- sd(KNN_har_sam_ANS_batch)
KNN_har_sam_ANS_condition_sd <- sd(KNN_har_sam_ANS_condition)
KNN_har_batch_O2_batch_sd <- sd(KNN_har_batch_O2_batch)
KNN_har_batch_O2_condition_sd <- sd(KNN_har_batch_O2_condition)
KNN_har_batch_ANS_batch_sd <- sd(KNN_har_batch_ANS_batch)
KNN_har_batch_ANS_condition_sd <- sd(KNN_har_batch_ANS_condition)


GMM_scvi_O2_batch_sd <- sd(GMM_scvi_O2_batch)
GMM_scvi_O2_condition_sd <- sd(GMM_scvi_O2_condition)
GMM_scvi_ANS_batch_sd <- sd(GMM_scvi_ANS_batch)
GMM_scvi_ANS_condition_sd <- sd(GMM_scvi_ANS_condition)
GMM_scvi_sam_O2_batch_sd <- sd(GMM_scvi_sam_O2_batch)
GMM_scvi_sam_O2_condition_sd <- sd(GMM_scvi_sam_O2_condition)
GMM_scvi_sam_ANS_batch_sd <- sd(GMM_scvi_sam_ANS_batch)
GMM_scvi_sam_ANS_condition_sd <- sd(GMM_scvi_sam_ANS_condition)
GMM_scvi_batch_O2_batch_sd <- sd(GMM_scvi_batch_O2_batch)
GMM_scvi_batch_O2_condition_sd <- sd(GMM_scvi_batch_O2_condition)
GMM_scvi_batch_ANS_batch_sd <- sd(GMM_scvi_batch_ANS_batch)
GMM_scvi_batch_ANS_condition_sd <- sd(GMM_scvi_batch_ANS_condition)

KNN_scvi_O2_batch_sd <- sd(KNN_scvi_O2_batch)
KNN_scvi_O2_condition_sd <- sd(KNN_scvi_O2_condition)
KNN_scvi_ANS_batch_sd <- sd(KNN_scvi_ANS_batch)
KNN_scvi_ANS_condition_sd <- sd(KNN_scvi_ANS_condition)
KNN_scvi_sam_O2_batch_sd <- sd(KNN_scvi_sam_O2_batch)
KNN_scvi_sam_O2_condition_sd <- sd(KNN_scvi_sam_O2_condition)
KNN_scvi_sam_ANS_batch_sd <- sd(KNN_scvi_sam_ANS_batch)
KNN_scvi_sam_ANS_condition_sd <- sd(KNN_scvi_sam_ANS_condition)
KNN_scvi_batch_O2_batch_sd <- sd(KNN_scvi_batch_O2_batch)
KNN_scvi_batch_O2_condition_sd <- sd(KNN_scvi_batch_O2_condition)
KNN_scvi_batch_ANS_batch_sd <- sd(KNN_scvi_batch_ANS_batch)
KNN_scvi_batch_ANS_condition_sd <- sd(KNN_scvi_batch_ANS_condition)

O2_sd <- c(GMM_PCA_O2_batch_sd,GMM_PCA_O2_condition_sd,
           GMM_scvi_O2_batch_sd,GMM_scvi_O2_condition_sd,
           KNN_PCA_O2_batch_sd,KNN_PCA_O2_condition_sd,
           KNN_scvi_O2_batch_sd,KNN_scvi_O2_condition_sd,
           GMM_har_sam_O2_batch_sd,GMM_har_sam_O2_condition_sd,
           GMM_scvi_sam_O2_batch_sd,GMM_scvi_sam_O2_condition_sd,
           KNN_har_sam_O2_batch_sd,KNN_har_sam_O2_condition_sd,
           KNN_scvi_sam_O2_batch_sd,KNN_scvi_sam_O2_condition_sd,
           GMM_har_batch_O2_batch_sd,GMM_har_batch_O2_condition_sd,
           GMM_scvi_batch_O2_batch_sd,GMM_scvi_batch_O2_condition_sd,
           KNN_har_batch_O2_batch_sd,KNN_har_batch_O2_condition_sd,
           KNN_scvi_batch_O2_batch_sd,KNN_scvi_batch_O2_condition_sd)


R_sd <- c(GMM_PCA_ANS_batch_sd,GMM_PCA_ANS_condition_sd,
           GMM_scvi_ANS_batch_sd,GMM_scvi_ANS_condition_sd,
           KNN_PCA_ANS_batch_sd,KNN_PCA_ANS_condition_sd,
           KNN_scvi_ANS_batch_sd,KNN_scvi_ANS_condition_sd,
           GMM_har_sam_ANS_batch_sd,GMM_har_sam_ANS_condition_sd,
           GMM_scvi_sam_ANS_batch_sd,GMM_scvi_sam_ANS_condition_sd,
           KNN_har_sam_ANS_batch_sd,KNN_har_sam_ANS_condition_sd,
           KNN_scvi_sam_ANS_batch_sd,KNN_scvi_sam_ANS_condition_sd,
           GMM_har_batch_ANS_batch_sd,GMM_har_batch_ANS_condition_sd,
           GMM_scvi_batch_ANS_batch_sd,GMM_scvi_batch_ANS_condition_sd,
           KNN_har_batch_ANS_batch_sd,KNN_har_batch_ANS_condition_sd,
           KNN_scvi_batch_ANS_batch_sd,KNN_scvi_batch_ANS_condition_sd)


```

```{r}
load("../../results/BatchStudy/Perea2022_stat_summary.Rda")
```

```{r}
R_sd_sample <- R_data_all$sd[1:24]
O2_sd_sample <- O2_data_all$sd[1:24]

sd_compare_data_R <- data.frame(R_data_all[c(1:24, 1:24),c(1:4,6)], sd = c(R_sd, R_sd_sample), type = rep(c("cell level", "sample level"), each = 24))
sd_compare_data_O2 <- data.frame(O2_data_all[c(1:24, 1:24),c(1:4,6)], sd = c(O2_sd, O2_sd_sample), type = rep(c("cell level", "sample level"), each = 24))

```

```{r}
ggplot(sd_compare_data_R, aes(x = DimReduc, y = sd, group = type))+
  geom_point(aes(col = type))+
  geom_line(aes(col = type))+
    scale_color_manual(values= safe_colorblind_palette,name = "Evaluate on")+
  theme_bw() +
  facet_grid(Group~Correction+Dens)+
  ylab("R Value Standard Deviation")+
      theme(axis.text.x = element_text(angle = 30, hjust=1))+
  ggtitle("Perez Lupus SLE data") 


ggplot(sd_compare_data_O2, aes(x = DimReduc, y = sd, group = type))+
  geom_point(aes(col = type))+
  geom_line(aes(col = type))+
    scale_color_manual(values= safe_colorblind_palette,name = "Evaluate on")+
  theme_bw() +
  facet_grid(Group~Correction+Dens)+
  ylab("O2 Value Standard Deviation")+
      theme(axis.text.x = element_text(angle = 30, hjust=1))+
  ggtitle("Perez Lupus SLE data") 
```



## Visualization

```{r}
load("../../results/BatchStudy/Perez2022_stat.Rda")
load("../../results/BatchStudy/Perez2022_stat_EV.Rda")
```

### Comparison



```{r}
Ori_R_boot <- data.frame(values = c(GMM_PCA_ANS_batch, GMM_PCA_ANS_condition,
                        KNN_PCA_ANS_batch, KNN_PCA_ANS_condition,
                        GMM_scvi_ANS_batch, GMM_scvi_ANS_condition,
                        KNN_scvi_ANS_batch, KNN_scvi_ANS_condition),
                      Dens = rep(rep(c("GMM","KNN"),each = 200),2),
                      Reduction = c(rep("PCA",400), rep("ScVI",400)),
                      Compare = rep(rep(c("Batch","Condition"),each = 100),4))

Ori_O2_boot <- data.frame(values = c(GMM_PCA_O2_batch, GMM_PCA_O2_condition,
                        KNN_PCA_O2_batch, KNN_PCA_O2_condition,
                        GMM_scvi_O2_batch, GMM_scvi_O2_condition,
                        KNN_scvi_O2_batch, KNN_scvi_O2_condition),
                      Dens = rep(rep(c("GMM","KNN"),each = 200),2),
                      Reduction = c(rep("PCA",400), rep("ScVI",400)),
                      Compare = rep(rep(c("Batch","Condition"),each = 100),4))

Ori_R <- R_data[R_data$DimReduc == "Original",]
Ori_R$comb <- paste0(Ori_R$Dens, ",", Ori_R$Correction)
Ori_R$Compare = Ori_R$Group
ggplot(Ori_R_boot, aes(x = paste0(Dens, ",", Reduction), y = values)) +
  geom_boxplot() +
  geom_point(data = Ori_R, aes(x = comb, y = Value), col = "red", size = 2)+
    geom_jitter(color="black", size=0.4, alpha=0.9) +
  facet_wrap(~Compare) +
  xlab("Combination") +
  ggtitle("ANOSIM R Value, No Batch Correction") +
  theme_bw()+
    ylim(c(min(c(Ori_O2_boot$values, Ori_R_boot$values,Ori_R$Value)), max(c(Ori_O2_boot$values, Ori_R_boot$values,Ori_R$Value))))

```

```{r }


Ori_O2 <- O2_data[O2_data$DimReduc == "Original",]
Ori_O2$comb <- paste0(Ori_O2$Dens, ",", Ori_O2$Correction)
Ori_O2$Compare = Ori_R$Group
ggplot(Ori_O2_boot, aes(x = paste0(Dens, ",", Reduction), y = values)) +
  geom_boxplot() +
  geom_point(data = Ori_O2, aes(x = comb, y = Value), col = "red", size = 2)+
    geom_jitter(color="black", size=0.4, alpha=0.9) +
  facet_wrap(~Compare) +
  xlab("Combination") +
  ggtitle("Oemga^2 Value, No Batch Correction") +
  theme_bw()+
  ylim(c(min(c(Ori_O2_boot$values, Ori_R_boot$values,Ori_O2$Value)), max(c(Ori_O2_boot$values, Ori_R_boot$values,Ori_O2$Value))))
```

```{r}
Sam_R_boot <- data.frame(values = c(GMM_har_sam_ANS_batch, GMM_har_sam_ANS_condition,
                        KNN_har_sam_ANS_batch, KNN_har_sam_ANS_condition,
                        GMM_scvi_sam_ANS_batch, GMM_scvi_sam_ANS_condition,
                        KNN_scvi_sam_ANS_batch, KNN_scvi_sam_ANS_condition),
                      Dens = rep(rep(c("GMM","KNN"),each = 200),2),
                      Reduction = c(rep("PCA",400), rep("ScVI",400)),
                      Compare = rep(rep(c("Batch","Condition"),each = 100),4))

Sam_O2_boot <- data.frame(values = c(GMM_har_sam_O2_batch, GMM_har_sam_O2_condition,
                        KNN_har_sam_O2_batch, KNN_har_sam_O2_condition,
                        GMM_scvi_sam_O2_batch, GMM_scvi_sam_O2_condition,
                        KNN_scvi_sam_O2_batch, KNN_scvi_sam_O2_condition),
                      Dens = rep(rep(c("GMM","KNN"),each = 200),2),
                      Reduction = c(rep("PCA",400), rep("ScVI",400)),
                      Compare = rep(rep(c("Batch","Condition"),each = 100),4))

Sam_R <- R_data[R_data$DimReduc == "Correct, Sample",]
Sam_R$comb <- paste0(Sam_R$Dens, ",", Sam_R$Correction)
Sam_R$Compare = Sam_R$Group
ggplot(Sam_R_boot, aes(x = paste0(Dens, ",", Reduction), y = values)) +
  geom_boxplot() +
  geom_point(data = Sam_R, aes(x = comb, y = Value), col = "red", size = 2)+
    geom_jitter(color="black", size=0.4, alpha=0.9) +
  facet_wrap(~Compare) +
  xlab("Combination") +
  ggtitle("ANOSIM R Value, Batch Correction on Sample") +
  theme_bw()+
    ylim(c(min(c(Sam_O2_boot$values, Sam_R_boot$values,Sam_R$Value)), max(c(Sam_O2_boot$values, Sam_R_boot$values,Sam_R$Value))))

```

```{r}


Sam_O2 <- O2_data[O2_data$DimReduc == "Correct, Sample",]
Sam_O2$comb <- paste0(Sam_O2$Dens, ",", Sam_O2$Correction)
Sam_O2$Compare = Sam_O2$Group
ggplot(Sam_O2_boot, aes(x = paste0(Dens, ",", Reduction), y = values)) +
  geom_boxplot() +
  geom_point(data = Sam_O2, aes(x = comb, y = Value), col = "red", size = 2)+
    geom_jitter(color="black", size=0.4, alpha=0.9) +
  facet_wrap(~Compare) +
  xlab("Combination") +
  ggtitle("Oemga^2 Value, Batch Correction on Sample") +
  theme_bw()+
      ylim(c(min(c(Sam_O2_boot$values, Sam_R_boot$values, Sam_O2$Value)), max(c(Sam_O2_boot$values, Sam_R_boot$values,Sam_O2$Value))))


```


```{r}
batch_R_boot <- data.frame(values = c(GMM_har_batch_ANS_batch, GMM_har_batch_ANS_condition,
                        KNN_har_batch_ANS_batch, KNN_har_batch_ANS_condition,
                        GMM_scvi_batch_ANS_batch, GMM_scvi_batch_ANS_condition,
                        KNN_scvi_batch_ANS_batch, KNN_scvi_batch_ANS_condition),
                      Dens = rep(rep(c("GMM","KNN"),each = 200),2),
                      Reduction = c(rep("PCA",400), rep("ScVI",400)),
                      Compare = rep(rep(c("Batch","Condition"),each = 100),4))

batch_O2_boot <- data.frame(values = c(GMM_har_batch_O2_batch, GMM_har_batch_O2_condition,
                        KNN_har_batch_O2_batch, KNN_har_batch_O2_condition,
                        GMM_scvi_batch_O2_batch, GMM_scvi_batch_O2_condition,
                        KNN_scvi_batch_O2_batch, KNN_scvi_batch_O2_condition),
                      Dens = rep(rep(c("GMM","KNN"),each = 200),2),
                      Reduction = c(rep("PCA",400), rep("ScVI",400)),
                      Compare = rep(rep(c("Batch","Condition"),each = 100),4))

batch_R <- R_data[R_data$DimReduc == "Correct, Batch",]
batch_R$comb <- paste0(batch_R$Dens, ",", batch_R$Correction)
batch_R$Compare = batch_R$Group
ggplot(batch_R_boot, aes(x = paste0(Dens, ",", Reduction), y = values)) +
  geom_boxplot() +
  geom_point(data = batch_R, aes(x = comb, y = Value), col = "red", size = 2)+
    geom_jitter(color="black", size=0.4, alpha=0.9) +
  facet_wrap(~Compare) +
  xlab("Combination") +
  ggtitle("ANOSIM R Value, Batch Correction on Batch") +
  theme_bw()+
  ylim(c(min(c(batch_O2_boot$values, batch_O2_boot$values,batch_R$Value, batch_O2$Value)), max(c(Sam_O2_boot$values, batch_R_boot$values,batch_R$Value, batch_O2$Value))))

```

```{r}

batch_O2 <- O2_data[O2_data$DimReduc == "Correct, Batch",]
batch_O2$comb <- paste0(batch_O2$Dens, ",", batch_O2$Correction)
batch_O2$Compare = batch_O2$Group
ggplot(batch_O2_boot, aes(x = paste0(Dens, ",", Reduction), y = values)) +
  geom_boxplot() +
  geom_point(data = batch_O2, aes(x = comb, y = Value), col = "red", size = 2)+
    geom_jitter(color="black", size=0.4, alpha=0.9) +
  facet_wrap(~Compare,scales = "free_y") +
  xlab("Combination") +
  ggtitle("Oemga^2 Value, Batch Correction on Batch") +
  theme_bw()+
  ylim(c(min(c(batch_O2_boot$values, batch_O2_boot$values, batch_R$Value, batch_O2$Value)), max(c(Sam_O2_boot$values, batch_R_boot$values, batch_R$Value, batch_O2$Value))))

```






### subtract median

```{r}
Ori_R_boot_med <- data.frame(values = c(GMM_PCA_ANS_batch-median(GMM_PCA_ANS_batch), GMM_PCA_ANS_condition - median(GMM_PCA_ANS_condition),
                        KNN_PCA_ANS_batch - median(KNN_PCA_ANS_batch), KNN_PCA_ANS_condition - median(KNN_PCA_ANS_condition),
                        GMM_scvi_ANS_batch -median(GMM_scvi_ANS_batch) , GMM_scvi_ANS_condition - median(GMM_scvi_ANS_condition),
                        KNN_scvi_ANS_batch - median(KNN_scvi_ANS_batch), KNN_scvi_ANS_condition - median(KNN_scvi_ANS_condition)),
                      Dens = rep(rep(c("GMM","KNN"),each = 200),2),
                      Reduction = c(rep("PCA",400), rep("ScVI",400)),
                      Compare = rep(rep(c("Batch","Condition"),each = 100),4))

Ori_O2_boot_med <- data.frame(values = c(GMM_PCA_O2_batch-median(GMM_PCA_O2_batch), GMM_PCA_O2_condition-median(GMM_PCA_O2_condition),
                        KNN_PCA_O2_batch-median(KNN_PCA_O2_batch), KNN_PCA_O2_condition-median(KNN_PCA_O2_condition),
                        GMM_scvi_O2_batch-median(GMM_scvi_O2_batch), GMM_scvi_O2_condition-median(GMM_scvi_O2_condition),
                        KNN_scvi_O2_batch-median(KNN_scvi_O2_batch), KNN_scvi_O2_condition-median(KNN_scvi_O2_condition)),
                      Dens = rep(rep(c("GMM","KNN"),each = 200),2),
                      Reduction = c(rep("PCA",400), rep("ScVI",400)),
                      Compare = rep(rep(c("Batch","Condition"),each = 100),4))


ggplot(Ori_R_boot_med, aes(x = paste0(Dens, ",", Reduction), y = values)) +
  geom_violin()+
  geom_boxplot(aes(col = Reduction, linetype = Dens),width=0.4, lwd = 0.7) +
 #   geom_jitter(aes(col = Reduction), size=0.4, alpha=0.3) +
    scale_color_manual(values = safe_colorblind_palette)+
  facet_wrap(~Compare) +
  xlab("Combination") +
  ggtitle("ANOSIM R Value, No Batch Correction") +
    theme_bw()+
  ylim(c(min(c(Ori_O2_boot_med$values, Ori_R_boot_med$values)), max(c(Ori_O2_boot_med$values, Ori_R_boot_med$values))))


```

```{r }


ggplot(Ori_O2_boot_med, aes(x = paste0(Dens, ",", Reduction), y = values)) +
  geom_violin()+
  geom_boxplot(aes(col = Reduction, linetype = Dens),width=0.4, lwd = 0.6) +
 #   geom_jitter(aes(col = Reduction), size=0.4, alpha=0.3) +
    scale_color_manual(values = safe_colorblind_palette)+
  facet_wrap(~Compare) +
  xlab("Combination") +
  ggtitle("Oemga^2 Value, No Batch Correction") +
  theme_bw()+
  ylim(c(min(c(Ori_O2_boot_med$values, Ori_R_boot_med$values)), max(c(Ori_O2_boot_med$values, Ori_R_boot_med$values))))
```

```{r}
Sam_R_boot_med <- data.frame(values = c(GMM_har_sam_ANS_batch-median(GMM_har_sam_ANS_batch), GMM_har_sam_ANS_condition-median(GMM_har_sam_ANS_condition),
                        KNN_har_sam_ANS_batch-median(KNN_har_sam_ANS_batch), KNN_har_sam_ANS_condition-median(KNN_har_sam_ANS_condition),
                        GMM_scvi_sam_ANS_batch-median(GMM_scvi_sam_ANS_batch), GMM_scvi_sam_ANS_condition-median(GMM_scvi_sam_ANS_condition),
                        KNN_scvi_sam_ANS_batch-median(KNN_scvi_sam_ANS_batch), KNN_scvi_sam_ANS_condition-median(KNN_scvi_sam_ANS_condition)),
                      Dens = rep(rep(c("GMM","KNN"),each = 200),2),
                      Reduction = c(rep("PCA",400), rep("ScVI",400)),
                      Compare = rep(rep(c("Batch","Condition"),each = 100),4))

Sam_O2_boot_med <- data.frame(values = c(GMM_har_sam_O2_batch-median(GMM_har_sam_O2_batch), GMM_har_sam_O2_condition-median(GMM_har_sam_O2_condition),
                        KNN_har_sam_O2_batch-median(KNN_har_sam_O2_batch), KNN_har_sam_O2_condition-median(KNN_har_sam_O2_condition),
                        GMM_scvi_sam_O2_batch-median(GMM_scvi_sam_O2_batch), GMM_scvi_sam_O2_condition-median(GMM_scvi_sam_O2_condition),
                        KNN_scvi_sam_O2_batch-median(KNN_scvi_sam_O2_batch), KNN_scvi_sam_O2_condition-median(KNN_scvi_sam_O2_condition)),
                      Dens = rep(rep(c("GMM","KNN"),each = 200),2),
                      Reduction = c(rep("PCA",400), rep("ScVI",400)),
                      Compare = rep(rep(c("Batch","Condition"),each = 100),4))


ggplot(Sam_R_boot_med, aes(x = paste0(Dens, ",", Reduction), y = values)) +
  geom_violin()+
  geom_boxplot(aes(col = Reduction, linetype = Dens),width=0.4, lwd = 0.7) +
#    geom_jitter(aes(col = Reduction), size=0.4, alpha=0.3) +
    scale_color_manual(values = safe_colorblind_palette)+
  facet_wrap(~Compare) +
  xlab("Combination") +
  ggtitle("ANOSIM R Value, Batch Correction on Sample") +
  theme_bw()+
  ylim(c(min(c(Sam_O2_boot_med$values, Sam_R_boot_med$values)), max(c(Sam_O2_boot_med$values, Sam_R_boot_med$values))))

```

```{r}

ggplot(Sam_O2_boot_med, aes(x = paste0(Dens, ",", Reduction), y = values)) +
  geom_violin()+
  geom_boxplot(aes(col = Reduction, linetype = Dens),width=0.4, lwd = 0.7) +
#    geom_jitter(aes(col = Reduction), size=0.4, alpha=0.3) +
    scale_color_manual(values = safe_colorblind_palette)+
  facet_wrap(~Compare) +
  xlab("Combination") +
  ggtitle("Oemga^2 Value, Batch Correction on Sample") +
  theme_bw()+
      ylim(c(min(c(Sam_O2_boot_med$values, Sam_R_boot_med$values)), max(c(Sam_O2_boot_med$values, Sam_R_boot_med$values))))

```


```{r}
batch_R_boot_med <- data.frame(values = c(GMM_har_batch_ANS_batch-median(GMM_har_batch_ANS_batch), GMM_har_batch_ANS_condition-median(GMM_har_batch_ANS_condition),
                        KNN_har_batch_ANS_batch-median(KNN_har_batch_ANS_batch), KNN_har_batch_ANS_condition-median(KNN_har_batch_ANS_condition),
                        GMM_scvi_batch_ANS_batch-median(GMM_scvi_batch_ANS_batch), GMM_scvi_batch_ANS_condition-median(GMM_scvi_batch_ANS_condition),
                        KNN_scvi_batch_ANS_batch-median(KNN_scvi_batch_ANS_batch), KNN_scvi_batch_ANS_condition-median(KNN_scvi_batch_ANS_condition)),
                      Dens = rep(rep(c("GMM","KNN"),each = 200),2),
                      Reduction = c(rep("PCA",400), rep("ScVI",400)),
                      Compare = rep(rep(c("Batch","Condition"),each = 100),4))

batch_O2_boot_med <- data.frame(values = c(GMM_har_batch_O2_batch-median(GMM_har_batch_O2_batch), GMM_har_batch_O2_condition-median(GMM_har_batch_O2_condition),
                        KNN_har_batch_O2_batch-median(KNN_har_batch_O2_batch), KNN_har_batch_O2_condition-median(KNN_har_batch_O2_condition),
                        GMM_scvi_batch_O2_batch-median(GMM_scvi_batch_O2_batch), GMM_scvi_batch_O2_condition-median(GMM_scvi_batch_O2_condition),
                        KNN_scvi_batch_O2_batch-median(KNN_scvi_batch_O2_batch), KNN_scvi_batch_O2_condition-median(KNN_scvi_batch_O2_condition)),
                      Dens = rep(rep(c("GMM","KNN"),each = 200),2),
                      Reduction = c(rep("PCA",400), rep("ScVI",400)),
                      Compare = rep(rep(c("Batch","Condition"),each = 100),4))

ggplot(batch_R_boot_med, aes(x = paste0(Dens, ",", Reduction), y = values)) +
  geom_violin()+
  geom_boxplot(aes(col = Reduction, linetype = Dens),width=0.4, lwd = 0.7) +
#    geom_jitter(aes(col = Reduction), size=0.4, alpha=0.3) +
    scale_color_manual(values = safe_colorblind_palette)+
  facet_wrap(~Compare) +
  xlab("Combination") +
  ggtitle("ANOSIM R Value, Batch Correction on Batch") +
  theme_bw()+
  ylim(c(min(c(batch_O2_boot_med$values, batch_O2_boot_med$values)), max(c(Sam_O2_boot_med$values, batch_R_boot_med$values))))

```

```{r}

ggplot(batch_O2_boot_med, aes(x = paste0(Dens, ",", Reduction), y = values)) +
  geom_violin()+
  geom_boxplot(aes(col = Reduction, linetype = Dens),width=0.4, lwd = 0.7) +
#    geom_jitter(aes(col = Reduction), size=0.4, alpha=0.3) +
    scale_color_manual(values = safe_colorblind_palette)+
  facet_wrap(~Compare,scales = "free_y") +
  xlab("Combination") +
  ggtitle("Oemga^2 Value, Batch Correction on Batch") +
  theme_bw()+
  ylim(c(min(c(batch_O2_boot_med$values, batch_O2_boot_med$values)), max(c(Sam_O2_boot_med$values, batch_R_boot_med$values))))

```


