---
title: "Untitled"
author: "Hao Wang"
date: "7/10/2022"
output: 
    html_document:
        toc: true
        toc_float: true
        toc_collapsed: true
        toc_depth: 3
        number_sections: true
        theme: cerulean
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(
  echo = FALSE, message = FALSE, warning = FALSE
)
library(ggplot2)
library(tidyr)
library(vegan)
library(stringr)
library(popPackage)
library(NMF)
library(umap)
library(RColorBrewer)
library(GGally)
library(grid)
library(gridExtra) 

# sbatch -p jsteinhardt --wrap="Rscript -e \"rmarkdown::render('paper_figures.Rmd')\""
#library(ggplotify)
#library(patchwork)
#darkcols <- bigPalette

colfunc <- colorRampPalette(c("white", "blue1", "purple","red")) # 
    
#color2 <- bigPalette[17:20]

colorBlindBlack8  <- c("#000000", "#E69F00", "#56B4E9",
                                "lightpink1","#CC79A7", 
                       "#009E73", "#F0E442", "#0072B2", "#D55E00")
safe_colorblind_palette <- c("#88CCEE", "#CC6677", "#DDCC77",
                             "#117733", "#332288", "#AA4499", 
                             "#44AA99", "#999933", "#882255",
                             "purple", "blue1", "#888888")                       
                       
#https://stackoverflow.com/questions/57153428/r-plot-color-combinations-that-are-colorblind-accessible
```


# Allenmouse

```{r}
meta = readRDS("../../data/Processed_Datasets/yaoMouseBrain/metadata/yaoMouseBrain_default_metadata.Rds")
meta <- unique(meta[,c("patient", "sample", "group")])
dist_mat_GMM_PCA <- readRDS("../../results/Processed_Datasets/yaoMouseBrain/yaoMouseBrain_default/yaoMouseBrain_default_PCA_GMM_matrix.Rds")
levels(meta$group)[which(levels(meta$group) == "RHP")] = "PPP-SP"
#meta$group[which(meta$group == "RHP")] = "PPP-SP"

meta$`brain region` <- ifelse(meta$group %in% c("HIP","ENT", "PPP-SP"), "HFP", "CTX")
#meta$joint_region_label[which(meta$group ==  "SSs-GU-VISC-AIp")] = "SSs-GU-VISC-AIp "
levels(meta$group)[which(levels(meta$group) == "SSs-GU-VISC-AIp")] = "SSs-GU-VISC-AIp "
```



## heatmap


```{r}
#dist_mat = dist_mat_GMM_PCA
pdf("../../results/fig/allenmouseheatmap_GMM.pdf", width = 10, height = 8, onefile = FALSE)
aheatmap(dist_mat_GMM_PCA[as.character(meta$sample),as.character(meta$sample)], color = colfunc(51),
         annCol = list("Categories" = meta$group,
                       "Categories" = meta$group,
                       "Categories" = meta$group,
                       "Brain Regions" = meta$`brain region`,
                       "Brain Regions" = meta$`brain region`,
                       "Brain Regions" = meta$`brain region`),
         annColors = list('Categories' = c(safe_colorblind_palette, colorBlindBlack8[-3]),
                          "Brain Regions" = colorBlindBlack8[8:9]),
         Colv = T, Rowv = FALSE,
         labRow = rep("", nrow(dist_mat_GMM_PCA)),
         labCol = rep("", nrow(dist_mat_GMM_PCA)),
         fontsize = 19, main = "",
         treeheight = 60)
dev.off()
```


## MDS




```{r}
meta = as.data.frame(meta)
df <- plotMDS(sqrt(dist_mat_GMM_PCA),n = 2, x = meta, sample_id = "sample", group_id = "group")$mds

pdf("../../results/fig/allenmousemds_GMM_sqrt.pdf", width = 7, height = 7)
ggplot(df, aes(x = Coordinate1, y = Coordinate2))+
 geom_point(aes(col = group, shape = brain.region),size = 5) +
  scale_shape_manual(values=c(16, 17))+
  scale_color_manual(values=c(safe_colorblind_palette,colorBlindBlack8[-3])) +
    theme_bw()  +
  guides(color = "none",
         shape = guide_legend(title = "Brain Regions"))+
#    guides(color=guide_legend(title="Categories")) +
  theme(text= element_text(size = 30),
        axis.title.x = element_text(vjust = -1),
        legend.position = "top",
        plot.margin = unit(c(0.5,0.5,0.5,0.1),"cm"))

dev.off()
```



# rahs data 12 samples


```{r }
meta = readRDS("../../data/Processed_Datasets/chengRash12/metadata/chengRash12_default_metadata.Rds")
meta <- unique(meta[, c("group", "sample")])
dist_mat_GMM_PCA <- readRDS("../../results/Processed_Datasets/chengRash12/chengRash12_default/chengRash12_default_PCA_GMM_matrix.Rds")
#meta$group = meta$tissue
meta$group = as.character(meta$group)
meta$sample = as.character(meta$sample)
meta$group[which(meta$group == "psoriasis")] = "trunk (psoriasis) "
meta$group[which(meta$group == "trunk")] = "trunk (normal)"
meta$group = str_to_title(meta$group)
```

## heatmap


```{r}

pdf("../../results/fig/rash_s12_heatmap_GMM.pdf", width = 9, height = 6, onefile =FALSE)
aheatmap(dist_mat_GMM_PCA, color = colfunc(51),
         annCol = list("Tissue Source" = meta$group,
                       "Tissue Source" = meta$group,
                       "Tissue Source" = meta$group),
         annColors = list("Tissue Source" = colorBlindBlack8[-4]),
         Colv = T, Rowv = FALSE,
         labRow = rep("", nrow(meta)), labCol = rep("", nrow(meta)),fontsize = 19, main = "", treeheight = 40)

dev.off()
```




```{r}
df = plotMDS(sqrt(dist_mat_GMM_PCA),n = 2, x = meta, sample_id = "sample", group_id = "group")$mds

pdf("../../results/fig/rash_s12_mds_GMM_sqrt.pdf", width = 7, height = 6)

ggplot(df, aes(x = Coordinate1, y = Coordinate2)) +
  geom_point(aes(col = group), size = 5) +
  theme_bw() + 
  theme(text = element_text(size = 27),
        legend.position = "none",
        plot.margin = unit(c(0.5,1,0.5,1),"cm"),
        axis.title.x = element_text(vjust = -1),
        axis.title.y = element_text(vjust = 2)) +
  scale_color_manual(values=colorBlindBlack8[-4])
dev.off()

```


# COVID_143

```{r}
meta = readRDS("../../data/Processed_Datasets/stephensonCOVIDPBMC/metadata/stephensonCOVIDPBMC_default_metadata.Rds")
meta <- unique(meta[, c("patient", "Status", "sample", "batch")])
dist_mat_GMM_PCA <- readRDS("../../results/Processed_Datasets/stephensonCOVIDPBMC/stephensonCOVIDPBMC_default/stephensonCOVIDPBMC_default_PCA_GMM_matrix.Rds")

levels(meta$batch)[1] = "Cambridge "
```

## all patients


```{r}
pdf("../../results/supplement/covid143heatmap_GMM.pdf",         # File name
    width = 8, height = 6, onefile = FALSE)  
aheatmap(dist_mat_GMM_PCA[as.character(meta$sample), as.character(meta$sample)], color = colfunc(51),
         annCol = list(Status = meta$Status,
                       Status = meta$Status,
                       Status = meta$Status,
                       Site = meta$batch,
                       Site = meta$batch,
                       Site = meta$batch),
         annColors = list(Status = safe_colorblind_palette,
                          Site = colorBlindBlack8[-4]),
         labRow = rep("", nrow(meta)), labCol = rep("", nrow(meta)),
         Colv = T, Rowv = FALSE,
         fontsize = 18,
         main = "")

dev.off()

df = plotMDS(sqrt(dist_mat_GMM_PCA),n = 2, x = meta, sample_id = "sample", group_id = "Status")$mds
covid_legend = ggplot(df, aes(x = Coordinate1, y = Coordinate2)) + 
  geom_point(aes(col = Status,
                 shape = batch), size =4) +
      scale_shape_manual(values=c(16, 7,3))+
  scale_color_manual(values=colorBlindBlack8) +
    theme_bw() +
  theme(text = element_text(size = 20))+
    guides(color = guide_legend(order=1),
         shape = guide_legend(order=2))
legend <- cowplot::get_legend(covid_legend)


pdf("../../results/fig/covid143_legend.pdf", width = 2, height = 5)
grid.newpage()
grid.draw(legend)
dev.off()

pdf("../../results/fig/covid143allGMMPCA.pdf", width = 7, height = 6)

ggplot(df, aes(x = Coordinate1, y = Coordinate2)) + 
  geom_point(aes(shape = batch,
                 col = Status), size =4) +
  scale_color_manual(values=colorBlindBlack8) +
    theme_bw() +
    scale_shape_manual(values=c(16, 7,3))+
  theme(text = element_text(size = 25),
        legend.position = "none",
        axis.title.x = element_text(vjust = -0.5))

dev.off()



```


## COVID and healthy patients

```{r}
subsamples <- meta$sample[meta$Status %in% c("Covid", "Healthy")]
meta_sub <- meta[meta$sample %in% subsamples,]
dist_mat_sub <- dist_mat_GMM_PCA[as.character(subsamples), as.character(subsamples)]


```








```{r}



df_sqrt = plotMDS(sqrt(dist_mat_sub),n = 2, x = meta_sub, sample_id = "sample", group_id = "Status")$mds
pdf("../../results/fig/covid143GMMpca.pdf", width = 7, height = 6)
ggplot(df_sqrt, aes(x = Coordinate1, y = Coordinate2)) + 
  geom_point(aes(shape = batch,
                 col = Status), size =4) +
  scale_color_manual(values=colorBlindBlack8) +
    theme_bw() +
    scale_shape_manual(values=c(16, 7,3))+
  theme(text = element_text(size = 25),
        legend.position = "none",
        axis.title.x = element_text(vjust = -0.5))


dev.off()
```



# COVID Lung atlas


```{r}
#meta = readRDS("../../data/Processed_Datasets/melmsCOVIDLung/metadata/melmsCOVIDLung_default_metadata.Rds")
#meta <- unique(meta[, c("group", "sample")])
dist_mat_GMM_PCA <- readRDS("../../results/Processed_Datasets/melmsCOVIDLung/melmsCOVIDLung_default/melmsCOVIDLung_default_PCA_GMM_matrix.Rds")
#meta <- data.frame("sample" = colnames(dist_mat_GMM_PCA))
meta <- data.frame("sample" = colnames(dist_mat_GMM_PCA))

meta$condition <- ifelse(str_detect(meta$sample, "cov"), "COVID", "Normal")

```

## mds



```{r}
df = plotMDS(sqrt(dist_mat_GMM_PCA),n = 2, x = meta, sample_id = "sample", group_id = "condition")$mds

pdf("../../results/fig/COVID_lung_mds_GMM_sqrt.pdf", width = 8, height = 6)

ggplot(df, aes(x = Coordinate1, y = Coordinate2))+
  geom_point(aes(col = condition), size = 5)+
  labs(color = "Types")+    
  theme_bw()+
  theme(text = element_text(size = 30),
        axis.title.x = element_text(vjust=  -0.6))+
    scale_color_manual(values=bigPalette)

dev.off()

```


# Pelka2021


```{r}
meta = readRDS("../../data/Processed_Datasets/pelkaCRC/metadata/pelkaCRC_default_metadata.Rds")
meta <- unique(meta[, c("patient", "group", "sample")])
dist_mat_GMM_PCA <- readRDS("../../results/Processed_Datasets/pelkaCRC/pelkaCRC_default/pelkaCRC_default_PCA_GMM_matrix.Rds")

meta <- unique(plot_df[, c("PatientTypeID", "MMRStatusTumor")])
meta = meta[meta$PatientTypeID %in% rownames(dist_mat_GMM_PCA),]
```


## MDS


```{r}
df = plotMDS(sqrt(dist_mat_GMM_PCA_pat),n = 2, x = meta, sample_id = "PatientTypeID", group_id = "MMRStatusTumor")$mds
pdf("../../results/fig/pelka_GMM_mds_sqrt.pdf", width = 8, height = 6)
ggplot(df, aes(x = Coordinate1, y = Coordinate2))+
  geom_point(aes(col = MMRStatusTumor), size = 5)+
  labs(color = "Types")+
    theme_bw()+
  theme(text = element_text(size = 30),
        axis.title.x = element_text(vjust = -0.6))+
    scale_color_manual(values=colorBlindBlack8)
    

dev.off()
```

```{r}

df = plotMDS(sqrt(dist_mat_GMM_PCA_pat),n = 10, x = meta, sample_id = "PatientTypeID", group_id = "MMRStatusTumor")$mds
df$MMRStatusTumor = as.factor(df$MMRStatusTumor)
pdf("../../results/supplement/pelka_mds5.pdf",width = 8, height = 6)

pairs(df[,paste0("Coordinate",1:5)],
      col =colorBlindBlack8[df$MMRStatusTumor],oma=c(4,4,6,15))
par(xpd=TRUE)
legend("bottomright", fill = colorBlindBlack8, legend =c("MMRd","MMRp","Normal"))

dev.off()


```
```{r}
library(umap)
pelka_umap = umap(df[,paste0("Coordinate",1:10)])$layout
colnames(pelka_umap) = paste0("UMAP_",1:2)
pelka_umap = cbind(pelka_umap, df)
pdf("../../results/supplement/pelka_umap.pdf",width = 8, height = 6)
ggplot(pelka_umap, aes(x = UMAP_1, y = UMAP_2))+
  geom_point(aes(col = MMRStatusTumor))+
  theme_bw()+
  theme(text = element_text(size = 20))+
  labs(color = "Types")
dev.off()
```


# Perez2022

```{r}

meta = readRDS("../../data/Processed_Datasets/perezLupus/metadata/perezLupus_default_metadata.Rds")
meta <- unique(meta[, c("patient", "group", "sample", "batch")])
levels(meta$group)[which(levels(meta$group) == "na")] = "normal"
meta$batch_id = 
dist_mat_GMM_PCA <- readRDS("../../results/Processed_Datasets/perezLupus/perez_default/perezLupus_default_PCA_GMM_matrix.Rds")

dist_mat_GMM_har <- readRDS("../../results/Processed_Datasets/perezLupus/perez_default/perezLupus_default_HarmonyBatch_GMM_matrix.Rds")
meta$group = str_to_title(meta$group)

#meta$batch_id = paste0(meta$donor_uuid, "_", meta$Processing_Cohort)
#levels(meta$disease_state)[which(levels(meta$disease_state) == "na")] = "normal"
```


## MDS


```{r }

data = plotMDS(sqrt(dist_mat_GMM_PCA),n = 2, x = meta, sample_id = "sample", group_id = "group")$mds
perez_legend = ggplot(data, aes(x = Coordinate1, y = Coordinate2)) +
  geom_point(aes(col = group, shape = batch),
             size = 4)+
  theme_bw()+
  theme(text = element_text(size = 20))+
  labs(color = "Condition", shape = "Batch")+
  scale_color_manual(values=colorBlindBlack8)+
      guides(color = guide_legend(order=1),
         shape = guide_legend(order=2))
legend <- cowplot::get_legend(perez_legend)


pdf("../../results/fig/perez_legend.pdf", width = 2, height = 5)
grid.newpage()
grid.draw(legend)
dev.off()

pdf("../../results/fig/perez_GMMpca_sqrt.pdf", width = 7, height = 6)
ggplot(data, aes(x = Coordinate1, y = Coordinate2), size = 2) +
  geom_point(aes(col = group, shape = batch),
             size = 4)+
  scale_color_manual(values=colorBlindBlack8) +
    theme_bw() +
  theme(text = element_text(size = 25),
        legend.position = "none",
        axis.title.x = element_text(vjust = -0.5))
dev.off()

pdf("../../results/fig/perez_GMMhar_sqrt.pdf", width = 7, height = 6)
data = plotMDS(sqrt(dist_mat_GMM_har),n = 2, x = meta, sample_id = "batch_id", group_id = "disease_state")$mds
ggplot(data, aes(x = Coordinate1, y = Coordinate2)) +
  geom_point(aes(col = group, shape = batch), size = 4)+
  scale_color_manual(values=colorBlindBlack8) +
    theme_bw() +
  theme(text = element_text(size = 25),
        legend.position = "none",
        axis.title.x = element_text(vjust = -0.5))
dev.off()


```


